name: CE9010_2018
channels:
- conda-forge
- defaults
dependencies:
- git
- python
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- scikit-learn
- networkx
- tweepy
- requests
- tqdm
- statsmodels
- librosa
- ffmpeg
- ipython
- jupyter
- jupyterlab_launcher=0.5.0
- sympy
- sqlalchemy
- xlrd
- tables
- facebook-sdk
- requests
# deep learning
- tensorflow
- keras

